ASF Source Code Documentation
Atmel Software Framework
Home
Features
ASF-Boards
ASF-CAN/LIN
ASF-Components
ASF-Drivers
ASF-DSP
ASF-FS
ASF-GFX
ASF-Sensors
ASF-Services
ASF-USB
3rd Party
CMSIS
Documentation
ASF Architecture
Reference Manual
API
Applications
Unit-Tests
Release Notes
Get Started
Download
Bug Tracker
Common IOPORT API
See Quick start guide for the common IOPORT service.
This is common IOPORT service for GPIO pin configuration and control in a standardized manner across the MEGA, MEGA_RF, XMEGA, UC3 and ARM devices.
Port pin control code is optimized for each platform, and should produce both compact and fast execution times when used with constant values.
Dependencies
This driver depends on the following modules:
sysclk_group for clock speed and functions.
IOPORT Modes
For details on these please see the device datasheet.
Modules
Quick Start Guide(s)
In this section you can find a list of all Quick Start guides related to the Common IOPORT API.
Macros
#define IOPORT_CREATE_PIN(port, pin) ((port) * 32 + (pin))
Create IOPORT pin number.
Enumerations
enum ioport_direction {
IOPORT_DIR_INPUT,
IOPORT_DIR_OUTPUT
}
IOPORT pin directions.
enum ioport_sense {
IOPORT_SENSE_BOTHEDGES,
IOPORT_SENSE_RISING,
IOPORT_SENSE_FALLING
}
enum ioport_value {
IOPORT_PIN_LEVEL_LOW,
IOPORT_PIN_LEVEL_HIGH
}
IOPORT levels.
Functions
static void ioport_disable_pin (ioport_pin_t pin)
Disable IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
static void ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask)
Disable multiple pins in a single IOPORT port.
static void ioport_enable_pin (ioport_pin_t pin)
Enable an IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
static void ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask)
Enable multiple pins in a single IOPORT port.
static bool ioport_get_pin_level (ioport_pin_t pin)
Get current value of an IOPORT pin, which has been configured as an input.
static ioport_port_mask_t ioport_get_port_level (ioport_pin_t port, ioport_port_mask_t mask)
Get current value of several IOPORT pins in a single port, which have been configured as an inputs.
static void ioport_init (void)
Initializes the IOPORT service, ready for use.
static ioport_port_mask_t ioport_pin_to_mask (ioport_pin_t pin)
Convert a pin ID into a bitmask mask for the given pin on its port.
static ioport_port_t ioport_pin_to_port_id (ioport_pin_t pin)
Convert a pin ID into a its port ID.
static void ioport_reset_pin_mode (ioport_pin_t pin)
Reset pin mode configuration for a single IOPORT pin.
static void ioport_reset_port_mode (ioport_port_t port, ioport_port_mask_t mask)
Reset multiple pin modes in a specified IOPORT port to defaults.
static void ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir)
Set direction for a single IOPORT pin.
static void ioport_set_pin_level (ioport_pin_t pin, bool level)
Set an IOPORT pin to a specified logical value.
static void ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode)
Set pin mode for one single IOPORT pin.
static void ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense)
Set the pin sense mode of a single IOPORT pin.
static void ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction dir)
Set I/O direction for a group of pins in a single IOPORT.
static void ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, ioport_port_mask_t level)
Set a group of IOPORT pins in a single port to a specified logical value.
static void ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode)
Set multiple pin modes in a single IOPORT port, such as pull-up, pull-down, etc.
static void ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense)
Set the pin sense mode of a multiple IOPORT pins on a single port.
static void ioport_toggle_pin_level (ioport_pin_t pin)
Toggle the value of an IOPORT pin, which has previously configured as an output.
static void ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask)
Toggle the values of several IOPORT pins located in a single port.
IOPORT Mode bit definitions
#define IOPORT_MODE_MUX_MASK (0xF << 0)
#define IOPORT_MODE_MUX_BIT0 (1 << 0)
#define IOPORT_MODE_MUX_BIT1 (1 << 1)
#define IOPORT_MODE_MUX_BIT2 (1 << 2)
#define IOPORT_MODE_MUX_BIT3 (1 << 3)
#define IOPORT_MODE_MUX_A (0 << 0)
#define IOPORT_MODE_MUX_B (1 << 0)
#define IOPORT_MODE_MUX_C (2 << 0)
#define IOPORT_MODE_MUX_D (3 << 0)
#define IOPORT_MODE_MUX_E (4 << 0)
#define IOPORT_MODE_MUX_F (5 << 0)
#define IOPORT_MODE_MUX_G (6 << 0)
#define IOPORT_MODE_MUX_H (7 << 0)
#define IOPORT_MODE_PULLUP (1 << 4)
#define IOPORT_MODE_PULLDOWN (1 << 5)
#define IOPORT_MODE_OPEN_DRAIN (1 << 6)
#define IOPORT_MODE_DRIVE_STRENGTH (1 << 7)
#define IOPORT_CREATE_PIN (port, pin) ((port) * 32 + (pin))
Create IOPORT pin number.
Create a IOPORT pin number for use with the IOPORT functions.
Parameters
port IOPORT port (e.g. PORTA, PA or PIOA depending on chosen architecture)
pin IOPORT zero-based index of the I/O pin
#define IOPORT_MODE_DRIVE_STRENGTH (1 << 7)
Extra drive strength
Referenced by arch_ioport_set_port_mode().
#define IOPORT_MODE_MUX_A (0 << 0)
MUX function A
#define IOPORT_MODE_MUX_B (1 << 0)
MUX function B
#define IOPORT_MODE_MUX_BIT0 (1 << 0)
MUX BIT0 mask
#define IOPORT_MODE_MUX_BIT1 (1 << 1)
MUX BIT1 mask
#define IOPORT_MODE_MUX_BIT2 (1 << 2)
MUX BIT2 mask
#define IOPORT_MODE_MUX_BIT3 (1 << 3)
MUX BIT3 mask
#define IOPORT_MODE_MUX_C (2 << 0)
MUX function C
#define IOPORT_MODE_MUX_D (3 << 0)
MUX function D
#define IOPORT_MODE_MUX_E (4 << 0)
MUX function E
#define IOPORT_MODE_MUX_F (5 << 0)
MUX function F
#define IOPORT_MODE_MUX_G (6 << 0)
MUX function G
#define IOPORT_MODE_MUX_H (7 << 0)
MUX function H
#define IOPORT_MODE_MUX_MASK (0xF << 0)
MUX bits mask
Referenced by arch_ioport_set_port_mode().
#define IOPORT_MODE_OPEN_DRAIN (1 << 6)
Open Drain
Referenced by arch_ioport_set_port_mode().
#define IOPORT_MODE_PULLDOWN (1 << 5)
Pull-down
Referenced by arch_ioport_set_port_mode().
#define IOPORT_MODE_PULLUP (1 << 4)
Pull-up
Referenced by arch_ioport_set_port_mode().
enum ioport_direction
IOPORT pin directions.
Enumerator
IOPORT_DIR_INPUT
IOPORT input direction
IOPORT_DIR_OUTPUT
IOPORT output direction
enum ioport_sense
Enumerator
IOPORT_SENSE_BOTHEDGES
IOPORT sense both rising and falling edges
IOPORT_SENSE_RISING
IOPORT sense rising edges
IOPORT_SENSE_FALLING
IOPORT sense falling edges
enum ioport_value
IOPORT levels.
Enumerator
IOPORT_PIN_LEVEL_LOW
IOPORT pin value low
IOPORT_PIN_LEVEL_HIGH
IOPORT pin value high
static void ioport_disable_pin (ioport_pin_t pin) inline static
Disable IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
Parameters
pin IOPORT pin to disable
References arch_ioport_disable_pin().
static void ioport_disable_port (ioport_port_t port, ioport_port_mask_t mask) inline static
Disable multiple pins in a single IOPORT port.
Parameters
port IOPORT port to disable
mask Pin mask of pins to disable
References arch_ioport_disable_port().
static void ioport_enable_pin (ioport_pin_t pin) inline static
Enable an IOPORT pin, based on a pin created with IOPORT_CREATE_PIN().
Parameters
pin IOPORT pin to enable
References arch_ioport_enable_pin().
static void ioport_enable_port (ioport_port_t port, ioport_port_mask_t mask) inline static
Enable multiple pins in a single IOPORT port.
Parameters
port IOPORT port to enable
mask Mask of pins within the port to enable
References arch_ioport_enable_port().
static bool ioport_get_pin_level (ioport_pin_t pin) inline static
Get current value of an IOPORT pin, which has been configured as an input.
Parameters
pin IOPORT pin to read
Returns
Current logical value of the specified pin
References arch_ioport_get_pin_level().
Referenced by button_pressed().
static ioport_port_mask_t ioport_get_port_level (ioport_pin_t port, ioport_port_mask_t mask) inline static
Get current value of several IOPORT pins in a single port, which have been configured as an inputs.
Parameters
port IOPORT port to read
mask Pin mask of pins to read
Returns
Logical levels of the specified pins from the read port, returned as a mask.
References arch_ioport_get_port_level().
static void ioport_init (void) inline static
Initializes the IOPORT service, ready for use.
This function must be called before using any other functions in the IOPORT service.
References arch_ioport_init().
static ioport_port_mask_t ioport_pin_to_mask (ioport_pin_t pin) inline static
Convert a pin ID into a bitmask mask for the given pin on its port.
Parameters
pin IOPORT pin ID to convert
Return values
Bitmask with a bit set that corresponds to the given pin ID in its port
References arch_ioport_pin_to_mask().
static ioport_port_t ioport_pin_to_port_id (ioport_pin_t pin) inline static
Convert a pin ID into a its port ID.
Parameters
pin IOPORT pin ID to convert
Return values
Port ID for the given pin ID
References arch_ioport_pin_to_port_id().
static void ioport_reset_pin_mode (ioport_pin_t pin) inline static
Reset pin mode configuration for a single IOPORT pin.
Parameters
pin IOPORT pin to configure
References arch_ioport_set_pin_mode().
static void ioport_reset_port_mode (ioport_port_t port, ioport_port_mask_t mask) inline static
Reset multiple pin modes in a specified IOPORT port to defaults.
Parameters
port IOPORT port to configure
mask Mask of pins whose mode configuration is to be reset
References arch_ioport_set_port_mode().
static void ioport_set_pin_dir (ioport_pin_t pin, enum ioport_direction dir) inline static
Set direction for a single IOPORT pin.
Parameters
pin IOPORT pin to configure
dir Direction to set for the specified pin (ioport_direction)
References arch_ioport_set_pin_dir().
Referenced by sio2ncp_init().
static void ioport_set_pin_level (ioport_pin_t pin, bool level) inline static
Set an IOPORT pin to a specified logical value.
Parameters
pin IOPORT pin to configure
level Logical value of the pin
References arch_ioport_set_pin_level().
Referenced by sio2ncp_init().
static void ioport_set_pin_mode (ioport_pin_t pin, ioport_mode_t mode) inline static
Set pin mode for one single IOPORT pin.
Parameters
pin IOPORT pin to configure
mode Mode masks to configure for the specified pin (IOPORT Modes)
References arch_ioport_set_pin_mode().
static void ioport_set_pin_sense_mode (ioport_pin_t pin, enum ioport_sense pin_sense) inline static
Set the pin sense mode of a single IOPORT pin.
Parameters
pin IOPORT pin to configure
pin_sense Edge to sense for the pin (ioport_sense)
References arch_ioport_set_pin_sense_mode().
static void ioport_set_port_dir (ioport_port_t port, ioport_port_mask_t mask, enum ioport_direction dir) inline static
Set I/O direction for a group of pins in a single IOPORT.
Parameters
port IOPORT port to configure
mask Pin mask of pins to configure
dir Direction to set for the specified pins (ioport_direction)
References arch_ioport_set_port_dir().
static void ioport_set_port_level (ioport_port_t port, ioport_port_mask_t mask, ioport_port_mask_t level) inline static
Set a group of IOPORT pins in a single port to a specified logical value.
Parameters
port IOPORT port to write to
mask Pin mask of pins to modify
level Level of the pins to be modified
References arch_ioport_set_port_level().
static void ioport_set_port_mode (ioport_port_t port, ioport_port_mask_t mask, ioport_mode_t mode) inline static
Set multiple pin modes in a single IOPORT port, such as pull-up, pull-down, etc.
configuration.
Parameters
port IOPORT port to configure
mask Pin mask of pins to configure
mode Mode masks to configure for the specified pins (IOPORT Modes)
References arch_ioport_set_port_mode().
static void ioport_set_port_sense_mode (ioport_port_t port, ioport_port_mask_t mask, enum ioport_sense pin_sense) inline static
Set the pin sense mode of a multiple IOPORT pins on a single port.
Parameters
port IOPORT port to configure
mask Bitmask if pins whose edge sense is to be configured
pin_sense Edge to sense for the pins (ioport_sense)
References arch_ioport_set_port_sense_mode().
static void ioport_toggle_pin_level (ioport_pin_t pin) inline static
Toggle the value of an IOPORT pin, which has previously configured as an output.
Parameters
pin IOPORT pin to toggle
References arch_ioport_toggle_pin_level().
static void ioport_toggle_port_level (ioport_port_t port, ioport_port_mask_t mask) inline static
Toggle the values of several IOPORT pins located in a single port.
Parameters
port IOPORT port to modify
mask Pin mask of pins to toggle
References arch_ioport_toggle_port_level().