ASF Source Code Documentation
Atmel Software Framework
Home
Features
ASF-Boards
ASF-CAN/LIN
ASF-Components
ASF-Drivers
ASF-DSP
ASF-FS
ASF-GFX
ASF-Sensors
ASF-Services
ASF-USB
3rd Party
CMSIS
Documentation
ASF Architecture
Reference Manual
API
Applications
Unit-Tests
Release Notes
Get Started
Download
Bug Tracker
SAM D20/D21/R21 Port Driver (PORT)
This driver for SAM D20/D21/R21 devices provides an interface for the configuration and management of the device's General Purpose Input/Output (GPIO) pin functionality, for manual pin state reading and writing.
The following peripherals are used by this module:
PORT (GPIO Management)
The outline of this documentation is as follows:
Prerequisites
Module Overview
Special Considerations
Extra Information
Examples
API Overview
Prerequisites
There are no prerequisites for this module.
Module Overview
The device GPIO (PORT) module provides an interface between the user application logic and external hardware peripherals, when general pin state manipulation is required. This driver provides an easy-to-use interface to the physical pin input samplers and output drivers, so that pins can be read from or written to for general purpose external hardware control.
Physical and Logical GPIO Pins
SAM D20/D21/R21 devices use two naming conventions for the I/O pins in the device; one physical, and one logical. Each physical pin on a device package is assigned both a physical port and pin identifier (e.g. "PORTA.0") as well as a monotonically incrementing logical GPIO number (e.g. "GPIO0"). While the former is used to map physical pins to their physical internal device module counterparts, for simplicity the design of this driver uses the logical GPIO numbers instead.
Physical Connection
The diagram below shows how this module is interconnected within the device.
Special Considerations
The SAM D20/D21/R21 port pin input sampler can be disabled when the pin is configured in pure output mode to save power; reading the pin state of a pin configured in output-only mode will read the logical output state that was last set.
Extra Information
For extra information see Extra Information for PORT Driver. This includes:
Acronyms
Dependencies
Errata
Module History
Examples
For a list of examples related to this driver, see Examples for PORT Driver.
API Overview
Modules
Quick Start Guide(s)
In this section you can find a list of all Quick Start guides related to the SAM D20/D21/R21 Port Driver (PORT).
Data Structures
struct port_config
Port pin configuration structure.
Enumerations
enum port_pin_dir {
PORT_PIN_DIR_INPUT = SYSTEM_PINMUX_PIN_DIR_INPUT,
PORT_PIN_DIR_OUTPUT = SYSTEM_PINMUX_PIN_DIR_OUTPUT,
PORT_PIN_DIR_OUTPUT_WTH_READBACK = SYSTEM_PINMUX_PIN_DIR_OUTPUT_WITH_READBACK
}
Port pin direction configuration enum.
enum port_pin_pull {
PORT_PIN_PULL_NONE = SYSTEM_PINMUX_PIN_PULL_NONE,
PORT_PIN_PULL_UP = SYSTEM_PINMUX_PIN_PULL_UP,
PORT_PIN_PULL_DOWN = SYSTEM_PINMUX_PIN_PULL_DOWN
}
Port pin input pull configuration enum.
PORT Alias Macros
#define PORTA PORT->Group[0]
Convenience definition for GPIO module group A on the device (if available).
#define PORTB PORT->Group[1]
Convenience definition for GPIO module group B on the device (if available).
#define PORTC PORT->Group[2]
Convenience definition for GPIO module group C on the device (if available).
#define PORTD PORT->Group[3]
Convenience definition for GPIO module group D on the device (if available).
State reading/writing (physical group orientated)
static PortGroup * port_get_group_from_gpio_pin (const uint8_t gpio_pin)
Retrieves the PORT module group instance from a given GPIO pin number.
static uint32_t port_group_get_input_level (const PortGroup *const port, const uint32_t mask)
Retrieves the state of a group of port pins that are configured as inputs.
static uint32_t port_group_get_output_level (const PortGroup *const port, const uint32_t mask)
Retrieves the state of a group of port pins that are configured as outputs.
static void port_group_set_output_level (PortGroup *const port, const uint32_t mask, const uint32_t level_mask)
Sets the state of a group of port pins that are configured as outputs.
static void port_group_toggle_output_level (PortGroup *const port, const uint32_t mask)
Toggles the state of a group of port pins that are configured as an outputs.
Configuration and initialization
static void port_get_config_defaults (struct port_config *const config)
Initializes a Port pin/group configuration structure to defaults.
void port_pin_set_config (const uint8_t gpio_pin, const struct port_config *const config)
Writes a Port pin configuration to the hardware module.
void port_group_set_config (PortGroup *const port, const uint32_t mask, const struct port_config *const config)
Writes a Port group configuration group to the hardware module.
State reading/writing (logical pin orientated)
static bool port_pin_get_input_level (const uint8_t gpio_pin)
Retrieves the state of a port pin that is configured as an input.
static bool port_pin_get_output_level (const uint8_t gpio_pin)
Retrieves the state of a port pin that is configured as an output.
static void port_pin_set_output_level (const uint8_t gpio_pin, const bool level)
Sets the state of a port pin that is configured as an output.
static void port_pin_toggle_output_level (const uint8_t gpio_pin)
Toggles the state of a port pin that is configured as an output.
#define PORTA PORT->Group[0]
Convenience definition for GPIO module group A on the device (if available).
#define PORTB PORT->Group[1]
Convenience definition for GPIO module group B on the device (if available).
#define PORTC PORT->Group[2]
Convenience definition for GPIO module group C on the device (if available).
#define PORTD PORT->Group[3]
Convenience definition for GPIO module group D on the device (if available).
enum port_pin_dir
Port pin direction configuration enum.
Enum for the possible pin direction settings of the port pin configuration structure, to indicate the direction the pin should use.
Enumerator
PORT_PIN_DIR_INPUT
The pin's input buffer should be enabled, so that the pin state can be read.
PORT_PIN_DIR_OUTPUT
The pin's output buffer should be enabled, so that the pin state can be set.
PORT_PIN_DIR_OUTPUT_WTH_READBACK
The pin's output and input buffers should be enabled, so that the pin state can be set and read back.
enum port_pin_pull
Port pin input pull configuration enum.
Enum for the possible pin pull settings of the port pin configuration structure, to indicate the type of logic level pull the pin should use.
Enumerator
PORT_PIN_PULL_NONE
No logical pull should be applied to the pin.
PORT_PIN_PULL_UP
Pin should be pulled up when idle.
PORT_PIN_PULL_DOWN
Pin should be pulled down when idle.
static void port_get_config_defaults (struct port_config *const config) inline static
Initializes a Port pin/group configuration structure to defaults.
Initializes a given Port pin/group configuration structure to a set of known default values. This function should be called on all new instances of these configuration structures before being modified by the user application.
The default configuration is as follows:
Input mode with internal pullup enabled
Parameters
[out] config Configuration structure to initialize to default values.
References Assert, port_config::direction, port_config::input_pull, PORT_PIN_DIR_INPUT, PORT_PIN_PULL_UP, and port_config::powersave.
Referenced by at25dfx_chip_init(), bootloader_system_init(), config_port_pins(), configure_port_pins(), init_buttons(), main(), oled1_init(), run_faultn_test(), run_faultx_test(), setup_extint_callback_mode_test(), setup_extint_polled_mode_test(), spi_attach_slave(), ssd1306_interface_init(), and usb_dual_enable().
static PortGroup* port_get_group_from_gpio_pin (const uint8_t gpio_pin) inline static
Retrieves the PORT module group instance from a given GPIO pin number.
Retrieves the PORT module group instance associated with a given logical GPIO pin number.
Parameters
[in] gpio_pin Index of the GPIO pin to convert.
Returns
Base address of the associated PORT module.
References system_pinmux_get_group_from_gpio_pin().
Referenced by port_pin_get_input_level(), port_pin_get_output_level(), port_pin_set_output_level(), and port_pin_toggle_output_level().
static uint32_t port_group_get_input_level (const PortGroup *const port, const uint32_t mask) inline static
Retrieves the state of a group of port pins that are configured as inputs.
Reads the current logic level of a port module's pins and returns the current levels as a bitmask.
Parameters
[in] port Base of the PORT module to read from.
[in] mask Mask of the port pin(s) to read.
Returns
Status of the port pin(s) input buffers.
References Assert, PortGroup::IN, and PORT_IN_Type::reg.
static uint32_t port_group_get_output_level (const PortGroup *const port, const uint32_t mask) inline static
Retrieves the state of a group of port pins that are configured as outputs.
Reads the current logical output level of a port module's pins and returns the current levels as a bitmask.
Parameters
[in] port Base of the PORT module to read from.
[in] mask Mask of the port pin(s) to read.
Returns
Status of the port pin(s) output buffers.
References Assert, PortGroup::OUT, and PORT_OUT_Type::reg.
void port_group_set_config (PortGroup *const port, const uint32_t mask, const struct port_config *const config)
Writes a Port group configuration group to the hardware module.
Writes out a given configuration of a Port group configuration to the hardware module.
Note
If the pin direction is set as an output, the pull-up/pull-down input configuration setting is ignored.
Parameters
[out] port Base of the PORT module to write to.
[in] mask Mask of the port pin(s) to configure.
[in] config Configuration settings for the pin group.
References Assert, system_pinmux_config::direction, port_config::direction, system_pinmux_config::input_pull, port_config::input_pull, system_pinmux_config::mux_position, port_config::powersave, system_pinmux_config::powersave, system_pinmux_get_config_defaults(), SYSTEM_PINMUX_GPIO, and system_pinmux_group_set_config().
static void port_group_set_output_level (PortGroup *const port, const uint32_t mask, const uint32_t level_mask) inline static
Sets the state of a group of port pins that are configured as outputs.
Sets the current output level of a port module's pins to a given logic level.
Parameters
[out] port Base of the PORT module to write to.
[in] mask Mask of the port pin(s) to change.
[in] level_mask Mask of the port level(s) to set.
References Assert, PortGroup::OUTCLR, PortGroup::OUTSET, PORT_OUTCLR_Type::reg, and PORT_OUTSET_Type::reg.
static void port_group_toggle_output_level (PortGroup *const port, const uint32_t mask) inline static
Toggles the state of a group of port pins that are configured as an outputs.
Toggles the current output levels of a port module's pins.
Parameters
[out] port Base of the PORT module to write to.
[in] mask Mask of the port pin(s) to toggle.
References Assert, PortGroup::OUTTGL, and PORT_OUTTGL_Type::reg.
static bool port_pin_get_input_level (const uint8_t gpio_pin) inline static
Retrieves the state of a port pin that is configured as an input.
Reads the current logic level of a port pin and returns the current level as a boolean value.
Parameters
[in] gpio_pin Index of the GPIO pin to read.
Returns
Status of the port pin's input buffer.
References PortGroup::IN, port_get_group_from_gpio_pin(), and PORT_IN_Type::reg.
Referenced by button_pressed(), check_boot_mode(), eic_callback_to_clear_halt(), extint_detection_callback(), get_button(), main(), oled1_get_button_state(), oled1_get_led_state(), sd_mmc_is_write_protected(), sd_mmc_select_slot(), and update_led_state().
static bool port_pin_get_output_level (const uint8_t gpio_pin) inline static
Retrieves the state of a port pin that is configured as an output.
Reads the current logical output level of a port pin and returns the current level as a boolean value.
Parameters
[in] gpio_pin Index of the GPIO pin to read.
Returns
Status of the port pin's output buffer.
References PortGroup::OUT, port_get_group_from_gpio_pin(), and PORT_OUT_Type::reg.
void port_pin_set_config (const uint8_t gpio_pin, const struct port_config *const config)
Writes a Port pin configuration to the hardware module.
Writes out a given configuration of a Port pin configuration to the hardware module.
Note
If the pin direction is set as an output, the pull-up/pull-down input configuration setting is ignored.
Parameters
[in] gpio_pin Index of the GPIO pin to configure.
[in] config Configuration settings for the pin.
References Assert, system_pinmux_config::direction, port_config::direction, system_pinmux_config::input_pull, port_config::input_pull, system_pinmux_config::mux_position, port_config::powersave, system_pinmux_config::powersave, system_pinmux_get_config_defaults(), SYSTEM_PINMUX_GPIO, and system_pinmux_pin_set_config().
Referenced by at25dfx_chip_init(), bootloader_system_init(), config_port_pins(), configure_port_pins(), init_buttons(), mac_init(), main(), oled1_init(), run_faultn_test(), run_faultx_test(), setup_extint_callback_mode_test(), setup_extint_polled_mode_test(), spi_attach_slave(), ssd1306_interface_init(), and usb_dual_enable().
static void port_pin_set_output_level (const uint8_t gpio_pin, const bool level) inline static
Sets the state of a port pin that is configured as an output.
Sets the current output level of a port pin to a given logic level.
Parameters
[in] gpio_pin Index of the GPIO pin to write to.
[in] level Logical level to set the given pin to.
References PortGroup::OUTCLR, PortGroup::OUTSET, port_get_group_from_gpio_pin(), PORT_OUTCLR_Type::reg, and PORT_OUTSET_Type::reg.
Referenced by _at25dfx_chip_deselect(), _at25dfx_chip_select(), at25dfx_chip_init(), extint_detection_callback(), mac_t_gts_cb(), main(), oled1_init(), oled1_set_led_state(), process_data_ind_not_transient(), program_memory(), run_extint_callback_mode_test(), run_extint_polled_mode_test(), run_faultn_test(), run_faultx_test(), setup_extint_callback_mode_test(), setup_extint_polled_mode_test(), spi_attach_slave(), spi_select_slave(), ssd1306_hard_reset(), ssd1306_init(), ssd1306_write_command(), ssd1306_write_data(), start_application(), update_led_state(), watchdog_early_warning_callback(), xosc32k_fail_callback(), and xosc32k_ok_callback().
static void port_pin_toggle_output_level (const uint8_t gpio_pin) inline static
Toggles the state of a port pin that is configured as an output.
Toggles the current output level of a port pin.
Parameters
[in] gpio_pin Index of the GPIO pin to toggle.
References PortGroup::OUTTGL, port_get_group_from_gpio_pin(), and PORT_OUTTGL_Type::reg.
Referenced by event_counter(), handle_gts_data_tx_end(), mac_process_data_frame(), main(), oled1_toggle_led_state(), process_data_ind_not_transient(), rtc_match_callback(), rtc_overflow_callback(), tc_callback_to_toggle_led(), tcc_callback_to_toggle_led(), and usart_write_callback().